### ISSUE TITLE
catalyst/mistserver: 2x PUSH_END triggers are fired by Mist after segmentation completes

### ISSUE THREAD

**Issue by emranemran** [livepeer/catalyst#201]
After catalyst-api adds the `catalyst_vod_*` stream as a source to Mist to begin segmenting, 2x PUSH_END triggers are fired by mist after segmentation is completed: 
``` 
4511 [2022-10-13 17:09:20] MistController (3602707) VERYHIGH: PUSH_END trigger handled by http://127.0.0.1:4949/api/mist/trigger
4512 [2022-10-13 17:09:20] MistController (3602707) VERYHIGH: PUSH_END trigger handled by http://127.0.0.1:4949/api/mist/trigger
4513 [2022-10-13 17:09:20] MistController (3602707) INFO: Executing PUSH_END trigger: http://127.0.0.1:4949/api/mist/trigger (asynchronous)
...
...
4524 [2022-10-13 17:09:20] MistController (3602707) INFO: Executing PUSH_END trigger: http://localhost:4949/api/mist/trigger (asynchronous)
``` 

When a PUSH_END is received by catalyst-api for a VOD stream, a transcode flow is initiated. With 2x PUSH_END events, 2x transcode pipelines are kicked off which can result in double the amount of transcoded renditions. 

See mist.log for the sequence of events

[mistproclivepeer.log](https://github.com/livepeer/catalyst/files/9782350/mistproclivepeer.log)
[mist.log](https://github.com/livepeer/catalyst/files/9782351/mist.log)

**Comment by Thulinma** [comment]
It looks like there are simply two `PUSH_END` triggers configured? What's the config used here?

If not that, it could be that there are two push attempts and one of them fails and the other succeeds... We should be able to tell from the trigger payloads. Are they identical payloads, or different?
