### ISSUE TITLE
Create UCAN web3.storage key-pairs

### ISSUE THREAD

**Issue by leszko** [livepeer/catalyst#361]
Web3.storage uses the UCAN Auth mechanism. For this we need to create a private/public key pair for each environment and store it in Vault. The key-pair needs to be in the format accepted by the [w3up CLI](https://github.com/web3-storage/w3cli).

I think the simplest way of generating these keys may be actually using the code from web3.storage ucan library. [Here's](https://github.com/web3-storage/ucanto/blob/582c4c504d2e75feee2c5d298ea08b2f01ff1c5e/packages/principal/src/rsa.js#L42) the function that generate the key-pair.

So, a code similar to this one could work (but please double-check if it's correct):
```javascript
import { generate } from '@ucanto/principal/rsa'

const res = await generate()
// Get DID and private key from res
```
-----------

**Acceptance criteria**
- public/private keys are in the format accepted  by the [w3up CLI](https://github.com/web3-storage/w3cli)
- public key (DID) is in the format: `did:key:z6Mkinv7ZyMuqg8H3ctSZW76UKwTQxRR7JLwv5yVtxAi3PKC`
- private key is in the format possible to store in Vault (probably just base64-encoded)
- public/private keys stored in Vault as: `UCAN_DID` (Public Key) and `UCAN_KEY` (Private Key)
- public/private keys are generated for each environment (`canary`, `staging`, `prod`) and stored in accordingly in Vault in `kv/canary`, `kv/staging`, `kv/prod`)
- the process of generating new keys is documented in the [SRE Handbook](https://www.notion.so/livepeer/SRE-Handbook-5b7b5de561dc4adc8b996c23c2622d20) (so we can later support key rotation)

------------

Resources about the UCAN Auth:
- [Web3 Storage Intro to UCAN](https://blog.web3.storage/posts/intro-to-ucan)
- [UCAN Spec](https://ucan.xyz/)

**Comment by red-0ne** [comment]
SRE Handbook entry for key generation https://www.notion.so/livepeer/Setup-Livepeer-Decentralized-Identity-76d47e446a3747f288b8491b78af39e2
