### ISSUE TITLE
Create integration tests

### ISSUE THREAD

**Issue by leszko** [livepeer/catalyst#38]
We need have a suite of integration tests and run them as part of the CI pipeline.

This GH Issue includes:
- Create an integration test to test the DMS stream replication
- Include the test in the [test GH Action workflow](https://github.com/livepeer/catalyst/blob/main/.github/workflows/test.yaml)

**Test scenario:**
1. Start 3 DMS instances
2. Send stream to a single instance
3. Read playback from each instance and check that it's correct

At first glance, it seems we could use [test-containers](https://github.com/testcontainers/testcontainers-go) and start a few DMS instances locally. We already used test-containers library inside [go-livepeer, for the purpose of E2E Testing](https://github.com/livepeer/go-livepeer/tree/master/test/e2e).

**Comment by iameli** [comment]
This sounds great! Depending on the resource requirements it might make sense to include it as a Drone workflow rather than a GH Actions workflow, but test-containers seems like a great way to go about it either way.

**Comment by leszko** [comment]
Closed by #44
