### ISSUE TITLE
Generate dynamic manifests based on webhook triggers from other projects

### ISSUE THREAD

**Issue by hjpotter92** [livepeer/catalyst#49]
- Setup a webhook for the project
- Webhook receives information about new branch/commit pushed to go-livepeer/mistserver/etc dependents
- Generate a dynamic manifest file (in gcp bucket?)
- Allow downloader to use manifest file URL in addition to local paths
- Extend downloader to override specific project metadata in manifest (on demand)

**Comment by leszko** [comment]
It's already done.
