### ISSUE TITLE
Implement auto-creation of `canary` branch

### ISSUE THREAD

**Issue by iameli** [livepeer/catalyst#56]
Blocked by https://github.com/livepeer/livepeer-infra/issues/917

Canary branch works like https://github.com/livepeer/catalyst/issues/55, except:
* Instead of scraping for the latest semver releases, we scrape the the bucket releases for each project's main branch.
* We don't need a PR for `canary` like we have with `staging`, because we expect upstream projects to push new semver releases when they're ready to go

**Comment by leszko** [comment]
Closing, this was done as part of https://github.com/livepeer/livepeer-infra/issues/917
