### ISSUE TITLE
Document new stream replication architecture

### ISSUE THREAD

**Issue by iameli** [livepeer/catalyst#69]
@leszko Please add a comment about the stream redirection logic

@emranemran Please add a comment about DTSC(S) stream replication

@hjpotter92 Please add a comment explaining the the e2e test flow in this repo

https://www.notion.so/livepeer/Multi-Node-Stream-Replication-Docs-43f2d8982da042f8894ad452f99cf9fc

**Comment by leszko** [comment]
Closing this one, because we actually need the whole arch documentation first. And it's tracked here: https://github.com/livepeer/livepeer-infra/issues/916
