### ISSUE TITLE
Add traefik proxy

### ISSUE THREAD

**Issue by iameli** [livepeer/catalyst#7]

**Comment by leszko** [comment]
@victorges @emranemran Do you know what this ticket is about and if it's related for the Catalyst release? And if yes, then how critical it is.

**Comment by victorges** [comment]
As this ticket was created 7 months ago, I think it might have been for the livepeer-in-a-box and not for catalyst? This is the same repo right?

As for the catalyst issue itself, i think it would be corresponding to that "figure out http server situation" ticket that Eli created somewhere as well.

**Comment by leszko** [comment]
> As this ticket was created 7 months ago, I think it might have been for the livepeer-in-a-box and not for catalyst? This is the same repo right?
> 
> As for the catalyst issue itself, i think it would be corresponding to that "figure out http server situation" ticket that Eli created somewhere as well.

Thanks for the comment @victorges . Then, closing this one. @iameli feel free to reopen if needed.
