### ISSUE TITLE
catalyst-node: handle `video` and `videorec` prefixes

### ISSUE THREAD

**Issue by iameli** [livepeer/catalyst#95]
Currently stream in Livepeer Studio can have two prefixes, corresponding to two Mist stream configurations: `video` for normal streams, and `videorec` for streams with recording enabled.

So our playback URLs look like this:
```
https://catalyst-node.example.com/hls/video+PLAYBACK_ID/index.m3u8
https://catalyst-node.example.com/hls/videorec+PLAYBACK_ID/index.m3u8
```

But in the dashboard, our playback URLs don't have any prefixes, and look like this:
```
https://catalyst-node.example.com/hls/PLAYBACK_ID/index.m3u8
```

The legacy system uses etcd routes and middleware in Traefik to handle this sort of thing, but we're getting rid of that. Other Mist configurations use the `defaultStream` parameter to automatically rewrite `PLAYBACK_ID` to e.g. `stream+PLAYBACK_ID`, but that won't work for us because we have two stream configurations, `video` and `videorec`.

I'm leaning toward handling this on the catalyst-node side, so it can issue a redirect from `https://global-playback-url.example.com/hls/PLAYBACK_ID/index.m3u8` to `https://catalyst-node.example.com/hls/PLAYBACK_ID/index.m3u8`.

**New command line option**: `-redirectPrefixes=video,videorec`. Then when we get an incoming playback request for `PLAYBACK_ID`, we'll query the Mist load balancer concurrently for `video+PLAYBACK_ID` and `videorec+PLAYBACK_ID`. (If an incoming request comes in for `video+playbackId` we can just forward it as-is.) Then we can issue a redirect to whichever one has a stream, if any.

**Comment by Thulinma** [comment]
You could also set `videorec$pluswildcard` as the fallback stream for `video`. Then, if `video+blah` isn't available, an internal redirect to `videorec+blah` would occur.

**Comment by hjpotter92** [comment]
From my discussions with @Thulinma; it seems like mist should be able to handle this; but the structure of configuration is slightly varied for catalyst deployment in staging. The original config used to have a `streams` key defining these prefixes https://github.com/livepeer/catalyst/blob/main/config/catalyst-one.json#L112-L119 which is no longer true for the new config files.

**Comment by iameli** [comment]
So it looks like this breaks with wildcard base streams that exist but their wildcard string doesn't:

```
▶ curl 'http://localhost:8042/video+b0dcxvwml48mxt2s'
lon-canary-catalyst-0.livepeer.fun

▶ curl 'http://localhost:8042/videorec+b0dcxvwml48mxt2s'
lon-canary-catalyst-0.livepeer.fun

▶ curl 'http://localhost:8042/videorec+doesnotexist'
mdw-canary-catalyst-0.livepeer.fun

▶ curl 'http://localhost:8042/doesnotexist'
FULL
```

So this is breaking video/videorec redirection — actually it's racing, whichever one comes back from MistUtilLoad first will return

**Comment by hjpotter92** [comment]
discussion threads on discord:

- https://discord.com/channels/423160867534929930/992554008776540180/1014477483237724180
- https://discord.com/channels/423160867534929930/992554008776540180/1015232206244958319

**Comment by iameli** [comment]
Re-fixed by
